version: "3"
services:
  redis:
    image: redis/redis-stack-server:latest
    container_name: Redis
    ports:
      - 6379:6379
    networks:
      - redis
  api:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 4000
    ports:
      - 4000:4000
    networks:
      - redis
    command: npm run start
networks:
  redis:
    driver: bridge
